### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/jaem_dev#5]
## Summary
CSS를 좀 더 효율적으로 관리하고 가독성을 높이기 위한 확장판인 SCSS 세팅

## Todo
- [x] sass,scss 필요 모듈 설치
- [x] scss 연동 테스트
- [x] scss 가장 대중적인 7-1 구조 세팅
- [x] style 초기화
- [x] css 글로벌 세팅
- [x] mixin, variable 기본 세팅
- [x] 일련의 과정을 모두 마치고 style 적용 여부 테스트

**Comment by jaemin96** [comment]
2023-2-1 >> scss 폴더 구조 세팅 및 css 초기화 작업

**Comment by jaemin96** [comment]
- [x] Complete Todos
